#!/usr/bin/env bash
#
# scripts/githooks/pre-commit
#

echo "Running pre-commit checks."

# Ensure the branch name is correct
echo -n "Checking that branch naming is correct..."
name=$(git branch --show-current)
echo $name | grep -P '^main$|^develop$|^hotfix/|^feature/|^bugfix/|^doc/'
if [ $? -ne 0 ]; then
    echo "'$name' is not an exceptable branch name"
    exit 1
fi
"branch name $name is ok."

# Ensure unit tests are all green. 100% coverage is not required at this point.
echo -n "Running unit tests..."
poetry run python -m pytest test/unit --cov --cov-report=term-missing \
  | grep -q "TOTAL.*100%" || exit 2
echo "all unit tests pass with 100% coverage."

# Lint away
echo -n "Running pylint..."
poetry run python -m pylint . || exit 3
echo "pylint ok."

echo -n "Running pydocstyle..."
poetry run pydocstyle || exit 4
echo "pydocstyle ok."
